vpc_name             = "dev-vpc"
ami_id               = "ami-0c02fb55956c7d316"
instance_type        = "t2.micro"
ec2_role_name        = "ec2-zipkin-role-dev"
security_group_name  = "ec2-zipkin-sg-dev"
environment          = "dev"