name: Terraform Destroy

on:
  workflow_dispatch: # Permite executar manualmente o workflow
    inputs:
      confirm_destroy:
        description: "Digite 'yes' para confirmar a destruição da infraestrutura"
        required: true
        default: "no"

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configurar AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        if: ${{ github.event.inputs.confirm_destroy == 'yes' }} # Executa apenas se o input for 'yes'
        run: terraform destroy -var-file="dev.tfvars" -auto-approve

      - name: Aviso de cancelamento
        if: ${{ github.event.inputs.confirm_destroy != 'yes' }} # Mostra mensagem se o input for diferente de 'yes'
        run: echo "A destruição da infraestrutura foi cancelada."